In [3]:
import numpy as np

In [7]:
#标量 5
s = np.array(5)
s, s.shape

(array(5), ())

In [ ]:
#vector
v = np.array([1,2,3])

#matrix
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

#tensor
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [17]:
v = np.array([1,2,3,4])
v, v.shape

(array([1, 2, 3, 4]), (4,))

In [18]:
x = v.reshape(1, 4)
x

array([[1, 2, 3, 4]])

In [19]:
x = v.reshape(4, 1)
x

array([[1],
       [2],
       [3],
       [4]])

In [21]:
x = v[None, :]
x

array([[1, 2, 3, 4]])

In [24]:
x = v[:, None]
x

array([[1],
       [2],
       [3],
       [4]])